### ISSUE TITLE
Scalar 

### ISSUE THREAD

**Issue by mariuszgromada** [xxczaki/awesome-calculators#8]
Scalar is a powerful math engine and math scripting language, that combines the simplicity of standard calculators with the flexibility of scripting. The power of Scalar comes from defining user defined arguments and user defined functions, which can be used in subsequent calculations

https://scalarmath.org/
https://play.google.com/store/apps/details?id=org.mathparser.scalar.pro
https://play.google.com/store/apps/details?id=org.mathparser.scalar.lite

**Comment by xxczaki** [comment]
@mariuszgromada Added in e02ce1e, thanks for your suggestion :smile:
